import { IProduct } from "@interfaces/index";

const products: Array<Omit<IProduct, "_id">> = [
  {
    name: "Product 1",
    description: "Product description 1",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 2",
    description: "Product description 2",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 3",
    description: "Product description 3",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 4",
    description: "Product description 4",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 5",
    description: "Product description 5",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 6",
    description: "Product description 6",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 7",
    description: "Product description 7",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 8",
    description: "Product description 8",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 9",
    description: "Product description 9",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 10",
    description: "Product description 10",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 11",
    description: "Product description 11",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 12",
    description: "Product description 12",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 13",
    description: "Product description 13",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 14",
    description: "Product description 14",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 15",
    description: "Product description 15",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 16",
    description: "Product description 16",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 17",
    description: "Product description 17",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 18",
    description: "Product description 18",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 19",
    description: "Product description 19",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 20",
    description: "Product description 20",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 21",
    description: "Product description 21",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 22",
    description: "Product description 22",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 23",
    description: "Product description 23",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 24",
    description: "Product description 24",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 25",
    description: "Product description 25",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 26",
    description: "Product description 26",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 27",
    description: "Product description 27",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 28",
    description: "Product description 28",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 29",
    description: "Product description 29",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 30",
    description: "Product description 30",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 31",
    description: "Product description 31",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 32",
    description: "Product description 32",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 33",
    description: "Product description 33",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 34",
    description: "Product description 34",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 35",
    description: "Product description 35",
    price: 999,
    currency: "USD",
  },
];

export default products;
