const products = [
  {
    name: "Product 1",
    description: "Prodict description 1",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 2",
    description: "Prodict description 2",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 3",
    description: "Prodict description 3",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 4",
    description: "Prodict description 4",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 5",
    description: "Prodict description 5",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 6",
    description: "Prodict description 6",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 7",
    description: "Prodict description 7",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 8",
    description: "Prodict description 8",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 9",
    description: "Prodict description 9",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 10",
    description: "Prodict description 10",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 11",
    description: "Prodict description 11",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 12",
    description: "Prodict description 12",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 13",
    description: "Prodict description 13",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 14",
    description: "Prodict description 14",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 15",
    description: "Prodict description 15",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 16",
    description: "Prodict description 16",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 17",
    description: "Prodict description 17",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 18",
    description: "Prodict description 18",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 19",
    description: "Prodict description 19",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 20",
    description: "Prodict description 20",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 21",
    description: "Prodict description 21",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 22",
    description: "Prodict description 22",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 23",
    description: "Prodict description 23",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 24",
    description: "Prodict description 24",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 25",
    description: "Prodict description 25",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 26",
    description: "Prodict description 26",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 27",
    description: "Prodict description 27",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 28",
    description: "Prodict description 28",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 29",
    description: "Prodict description 29",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 30",
    description: "Prodict description 30",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 31",
    description: "Prodict description 31",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 32",
    description: "Prodict description 32",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 33",
    description: "Prodict description 33",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 34",
    description: "Prodict description 34",
    price: 999,
    currency: "USD",
  },
  {
    name: "Product 35",
    description: "Prodict description 35",
    price: 999,
    currency: "USD",
  },
];

export default products;
